-- SELECT

SELECT usu_id, usu_nome, usu_login, usu_senha, usu_adm FROM USUARIOS; 

SELECT set_id, set_nome, set_localizacao FROM SETORES;

SELECT forn_id, forn_cnpj, forn_razao_social, forn_nome, forn_celular, forn_fixo, forn_email, forn_cidade FROM FORNECEDORES;

SELECT prod_id, prod_nome, prod_estoque, prod_estoque_retirada, set_id FROM PRODUTOS;

SELECT forn_id, prod_id FROM FORNECEDORES_PRODUTO;

SELECT atv_id, atv_dthr, atv_status, prod_id, usu_id, set_id FROM ATIVIDADES;

SELECT ret_id, ret_qtd, prod_id, atv_id FROM RETIRADAS_ESTOQUE; 

SELECT atv_tp_id, atv_tp_tipo FROM ATIVIDADE_TIPOS; 


-- DROP
DROP TABLE FORNECEDORES_PRODUTO;
DROP TABLE RETIRADAS_ESTOQUE; 
DROP TABLE ATIVIDADES;
DROP TABLE PRODUTOS;
DROP TABLE FORNECEDORES;
DROP TABLE SETORES;
DROP TABLE USUARIOS; 
DROP TABLE ATIVIDADE_TIPOS;

-- DESCRIBE
DESCRIBE USUARIOS;
DESCRIBE SETORES;
DESCRIBE FORNECEDORES;
DESCRIBE PRODUTOS;
DESCRIBE FORNECEDORES_PRODUTO;
DESCRIBE ATIVIDADES;
DESCRIBE RETIRADAS_ESTOQUE; 
DESCRIBE ATIVIDADE_TIPOS;

-- APAGAR REGISTROS
DELETE FROM USUARIOS;
DELETE FROM SETORES;
DELETE FROM FORNECEDORES;
DELETE FROM PRODUTOS;
DELETE FROM FORNECEDORES_PRODUTO;
DELETE FROM ATIVIDADES;
DELETE FROM RETIRADAS_ESTOQUE;

-- RESETAR AUTO INCREMENTO (somente para tabelas criadas com Auto-incremento)

ALTER TABLE USUARIOS AUTO_INCREMENT = 1;

